/**
 * Typed access to the tuning constants exported from the Python game.
 *
 * `data/config.json` is generated by `tools/export_data.py` and is the single
 * source of truth for balance. Nothing here invents a number: if a constant is
 * missing from the export that is a bug in the exporter, and `assertConfig()`
 * says so loudly at boot rather than letting a silent default change the feel
 * of the game.
 */

import raw from "../data/config.json";

type RawConfig = Record<string, unknown>;
const C = (raw as { config: RawConfig }).config;

const missing: string[] = [];

function num(key: string, fallback: number): number {
  const v = C[key];
  if (typeof v === "number" && Number.isFinite(v)) return v;
  missing.push(key);
  return fallback;
}

function int(key: string, fallback: number): number {
  return Math.round(num(key, fallback));
}

function bool(key: string, fallback: boolean): boolean {
  const v = C[key];
  if (typeof v === "boolean") return v;
  missing.push(key);
  return fallback;
}

function str(key: string, fallback: string): string {
  const v = C[key];
  if (typeof v === "string") return v;
  missing.push(key);
  return fallback;
}

// ---------------------------------------------------------------------------
// Identity
// ---------------------------------------------------------------------------
export const GAME_TITLE = str("GAME_TITLE", "NEON SERPENT");
export const GAME_SUBTITLE = str("GAME_SUBTITLE", "a mouse-driven arcade odyssey");

// ---------------------------------------------------------------------------
// The virtual canvas everything is authored against
// ---------------------------------------------------------------------------
export const WINDOW_W = int("WINDOW_W", 1280);
export const WINDOW_H = int("WINDOW_H", 720);
export const CANVAS_ASPECT = WINDOW_W / WINDOW_H;
export const FPS = int("FPS", 60);
export const MAX_DT = num("MAX_DT", 1 / 20);

export const HUD_H = int("HUD_H", 78);
export const ARENA_MARGIN = int("ARENA_MARGIN", 14);
export const ARENA_X = int("ARENA_X", 14);
export const ARENA_Y = int("ARENA_Y", 78);
export const ARENA_W = int("ARENA_W", 1252);
export const ARENA_H = int("ARENA_H", 628);

// ---------------------------------------------------------------------------
// Snake
// ---------------------------------------------------------------------------
export const SNAKE_BASE_SPEED = num("SNAKE_BASE_SPEED", 210);
export const SNAKE_SPEED_PER_LEVEL = num("SNAKE_SPEED_PER_LEVEL", 9);
export const SNAKE_MAX_SPEED = num("SNAKE_MAX_SPEED", 460);
export const SNAKE_BOOST_MULT = num("SNAKE_BOOST_MULT", 1.85);
export const SNAKE_BOOST_DRAIN = num("SNAKE_BOOST_DRAIN", 46);
export const SNAKE_BOOST_REGEN = num("SNAKE_BOOST_REGEN", 26);
export const SNAKE_BOOST_MAX = num("SNAKE_BOOST_MAX", 100);
export const SNAKE_BOOST_MIN_TO_START = num("SNAKE_BOOST_MIN_TO_START", 12);

/**
 * Steering. Turn radius is speed/omega, so a constant angular rate makes the
 * snake turn wider the faster it moves. Holding the *radius* constant and
 * deriving omega from speed is what keeps a hairpin at 40-76 px at every
 * speed in the game. See the note in snake/config.py for the measurements.
 */
export const SNAKE_MIN_TURN_RADIUS = num("SNAKE_MIN_TURN_RADIUS", 20);
export const SNAKE_TURN_RATE_CAP = num("SNAKE_TURN_RATE_CAP", 20);
export const SNAKE_TURN_RATE = num("SNAKE_TURN_RATE", 5.4);
export const SNAKE_TURN_RATE_SLOW = num("SNAKE_TURN_RATE_SLOW", 8.2);

export const SNAKE_START_LENGTH = int("SNAKE_START_LENGTH", 6);
export const SNAKE_SEGMENT_SPACING = num("SNAKE_SEGMENT_SPACING", 13);
export const SNAKE_HEAD_RADIUS = num("SNAKE_HEAD_RADIUS", 13);
export const SNAKE_BODY_RADIUS = num("SNAKE_BODY_RADIUS", 11);
export const SNAKE_TAIL_RADIUS = num("SNAKE_TAIL_RADIUS", 5);
export const SNAKE_GROW_PER_FOOD = int("SNAKE_GROW_PER_FOOD", 2);

export const SELF_COLLISION_SKIP = int("SELF_COLLISION_SKIP", 16);
export const SELF_COLLISION_DEPTH = num("SELF_COLLISION_DEPTH", 0.62);

// ---------------------------------------------------------------------------
// Steering input
// ---------------------------------------------------------------------------
export const MOUSE_DEADZONE = num("MOUSE_DEADZONE", 18);
export const CURSOR_TRAIL_LEN = int("CURSOR_TRAIL_LEN", 14);

// ---------------------------------------------------------------------------
// Food / scoring
// ---------------------------------------------------------------------------
export const FOOD_RADIUS = num("FOOD_RADIUS", 9);
export const FOOD_PICKUP_PAD = num("FOOD_PICKUP_PAD", 6);
export const FOOD_PULSE_SPEED = num("FOOD_PULSE_SPEED", 3.4);
export const SCORE_PER_FOOD = int("SCORE_PER_FOOD", 10);
export const COMBO_WINDOW = num("COMBO_WINDOW", 3);
export const COMBO_MAX = int("COMBO_MAX", 8);
export const COMBO_STEP_BONUS = int("COMBO_STEP_BONUS", 5);

// ---------------------------------------------------------------------------
// Power-ups
// ---------------------------------------------------------------------------
export const POWERUP_RADIUS = num("POWERUP_RADIUS", 13);
export const POWERUP_SPAWN_MIN = num("POWERUP_SPAWN_MIN", 7);
export const POWERUP_SPAWN_MAX = num("POWERUP_SPAWN_MAX", 14);
export const POWERUP_LIFETIME = num("POWERUP_LIFETIME", 11);
export const POWERUP_DEFAULT_DURATION = num("POWERUP_DEFAULT_DURATION", 7);

// ---------------------------------------------------------------------------
// Lives / damage
// ---------------------------------------------------------------------------
export const START_LIVES = int("START_LIVES", 3);
export const INVULN_AFTER_HIT = num("INVULN_AFTER_HIT", 2.2);
export const HIT_LENGTH_PENALTY = int("HIT_LENGTH_PENALTY", 4);

// ---------------------------------------------------------------------------
// Effects budgets
// ---------------------------------------------------------------------------
export const MAX_PARTICLES = int("MAX_PARTICLES", 1400);
export const TRAIL_EMIT_RATE = num("TRAIL_EMIT_RATE", 46);
export const SHAKE_DECAY = num("SHAKE_DECAY", 5.5);
export const FLASH_DECAY = num("FLASH_DECAY", 3.2);

// ---------------------------------------------------------------------------
// UI
// ---------------------------------------------------------------------------
export const UI_CORNER = int("UI_CORNER", 12);
export const UI_BUTTON_W = int("UI_BUTTON_W", 300);
export const UI_BUTTON_H = int("UI_BUTTON_H", 58);
/** Per-button click debounce, seconds. */
export const UI_CLICK_COOLDOWN = num("UI_CLICK_COOLDOWN", 0.1);
export const TRANSITION_TIME = num("TRANSITION_TIME", 0.55);

// ---------------------------------------------------------------------------
// Modes / difficulty keys
// ---------------------------------------------------------------------------
export const MODE_STORY = str("MODE_STORY", "story");
export const MODE_FREE = str("MODE_FREE", "free");
export const DEFAULT_MODE = str("DEFAULT_MODE", MODE_STORY);

export const DIFF_EASY = str("DIFF_EASY", "easy");
export const DIFF_NORMAL = str("DIFF_NORMAL", "normal");
export const DIFF_HARD = str("DIFF_HARD", "hard");
export const DIFF_EXPERT = str("DIFF_EXPERT", "expert");
export const DEFAULT_DIFFICULTY = str("DEFAULT_DIFFICULTY", DIFF_NORMAL);

export const DEBUG_HITBOXES = bool("DEBUG_HITBOXES", false);

// ---------------------------------------------------------------------------
// Touch / responsive additions (web only - no Python counterpart)
// ---------------------------------------------------------------------------
/**
 * Physical-size driven, from the touch study: on a phone the snake is ~2.3 mm
 * wide and a hand covers ~72% of the arena's height, versus ~36% on a tablet.
 * That 2x occlusion gap is why phone and tablet get different schemes.
 */
export const TOUCH_STEER_DEADZONE_PX = 12;   // CSS px before a drag steers
export const TOUCH_ANCHOR_RECENTRE = 60;     // CSS px/s the anchor chases the finger
export const TOUCH_AIM_DISTANCE = 400;       // canvas px projected ahead of the head
export const TOUCH_TABLET_OFFSET = 85;       // canvas px aim offset on tablets
export const TOUCH_MIN_TARGET_PX = 44;       // minimum hit target, CSS px
export const TABLET_MIN_MIN_EDGE_PX = 600;   // >= this short edge counts as a tablet

/** Report any constant the export failed to provide. */
export function configProblems(): string[] {
  return [...new Set(missing)];
}

export function assertConfig(): void {
  const bad = configProblems();
  if (bad.length) {
    console.error(
      `[config] ${bad.length} constant(s) missing from data/config.json, ` +
        `using fallbacks: ${bad.join(", ")}. Re-run tools/export_data.py.`,
    );
  }
}
