/**
 * Level design for NEON SERPENT - a port of `snake/core/level.py`.
 *
 * Twelve hand-authored stages. Each one is a {@link LevelDef}: a pile of tuning
 * numbers plus an `obstacleSpec` - a list of plain records that
 * `core/obstacles.buildObstacles` turns into live hazards.
 *
 * The layouts, goals and derived numbers all come from `data/levels.json`
 * (generated by `tools/export_data.py`); nothing is retyped here. The derived
 * values (`cruiseSpeed`, `baseSpeed`, `parScore`, `starTargets`, `number`) are
 * *also* recomputed at load from the same formulas the Python properties use,
 * and the two are asserted to agree - so a future exporter change, or a drift
 * in `config.json`, fails loudly at boot instead of silently rebalancing the
 * campaign.
 *
 * Spec conventions (matching `obstacles._resolve`): positions and box sizes are
 * fractions of the arena (`x`/`y`/`w`/`h`/`travel`); radii, lengths and
 * thicknesses are pixels (always > 1.0) so the arena's 2:1 aspect never
 * rescales them.
 */

import rawLevels from "../data/levels.json";
import * as C from "./config";
import { clamp } from "./mathx";
import { THEMES, themeForLevel, type Theme } from "./palette";

/**
 * One entry of a level's obstacle spec.
 *
 * Kept deliberately loose - `obstacles.buildObstacles` owns the per-type
 * schema, and the keys stay in the Python `snake_case` the exporter emitted
 * (`min_radius`, `hub_radius`, `fire_time`, ...) so a reviewer can diff the
 * JSON against `level.py` line for line.
 */
export interface ObstacleSpecEntry {
  /** Hazard kind: "wall" | "movingbar" | "spinner" | "pulsar" | "lasergate" | "portal". */
  readonly type: string;
  readonly [key: string]: unknown;
}

/** Everything the game scene needs to build and score one stage. */
export interface LevelDef {
  /** Zero-based index into {@link LEVELS}. */
  readonly index: number;
  readonly name: string;
  readonly subtitle: string;
  /** The level's colour identity - always `THEMES[index]`. */
  readonly theme: Theme;
  /** Food eaten to clear the stage. */
  readonly goalFood: number;
  /** Pace multiplier applied on top of {@link LevelDef.cruiseSpeed}. */
  readonly speedMult: number;
  /** How many food pellets are alive at once. */
  readonly foodCount: number;
  readonly obstacleSpec: readonly ObstacleSpecEntry[];
  readonly powerupsEnabled: boolean;
  /** True when the arena edges teleport instead of killing. */
  readonly wrapWalls: boolean;
  readonly hint: string;

  // -- derived (mirrors of the Python properties/methods) -------------------
  /** One-based level number, for display. */
  readonly number: number;
  /** 0..1 across the campaign; handy for UI colour ramps. */
  readonly difficultyRating: number;
  /**
   * The snake's own cruise speed for this level, *before* `speedMult`.
   *
   * This is what the gameplay scene assigns to `snake.speed`. The pace
   * multiplier is not folded in here: it is passed separately as
   * `snake.update(dt, levelDef.speedMult * effects.speedMultiplier())` so
   * power-ups compose with it cleanly.
   */
  readonly cruiseSpeed: number;
  /**
   * Pixels/second the snake actually travels here, power-ups aside.
   *
   * `SNAKE_MAX_SPEED` bounds the cruise term only; `speedMult` is applied on
   * top of it. Clamping the product instead would flatten levels 11 and 12
   * onto the same 460 px/s.
   */
  readonly baseSpeed: number;
  /** Score for clearing the goal with no combo at all - the 1-star bar. */
  readonly parScore: number;
  /** Score thresholds for one, two and three stars. */
  readonly starTargets: readonly [number, number, number];
}

// ---------------------------------------------------------------------------
// Arena geometry every layout is measured against
// ---------------------------------------------------------------------------

/** The snake spawns here; levels keep lethal geometry outside this disc. */
export const SPAWN_POS: readonly [number, number] = [
  C.ARENA_X + C.ARENA_W * 0.5,
  C.ARENA_Y + C.ARENA_H * 0.5,
];

/** Radius of the guaranteed-clear plaza around {@link SPAWN_POS}, in pixels. */
export const SPAWN_CLEAR_RADIUS = 70.0;

/** Narrowest lane any layout is allowed to leave, in pixels. */
export const MIN_LANE: number = 2.0 * C.SNAKE_HEAD_RADIUS + 24.0;

// ---------------------------------------------------------------------------
// The derived formulas, kept next to each other so the assert below is honest
// ---------------------------------------------------------------------------

/** Cruise speed for a zero-based level index. Port of `LevelDef.cruise_speed`. */
export function cruiseSpeedFor(index: number): number {
  const raw = C.SNAKE_BASE_SPEED + C.SNAKE_SPEED_PER_LEVEL * index;
  return clamp(raw, 60.0, C.SNAKE_MAX_SPEED);
}

/** Par score for a food goal. Port of `LevelDef.par_score`. */
export function parScoreFor(goalFood: number): number {
  return goalFood * C.SCORE_PER_FOOD;
}

/** Star thresholds for a par score. Port of `LevelDef.star_targets`. */
export function starTargetsFor(par: number): [number, number, number] {
  return [par, Math.trunc(par * 1.35), Math.trunc(par * 1.75)];
}

// ---------------------------------------------------------------------------
// Loading the export
// ---------------------------------------------------------------------------

type RawRecord = Record<string, unknown>;

function need(src: RawRecord, key: string, where: string): unknown {
  const v = src[key];
  if (v === undefined) throw new Error(`levels.json: ${where} is missing "${key}"`);
  return v;
}

function readNum(src: RawRecord, key: string, where: string): number {
  const v = need(src, key, where);
  if (typeof v === "number" && Number.isFinite(v)) return v;
  throw new Error(`levels.json: ${where}."${key}" is not a finite number`);
}

function readStr(src: RawRecord, key: string, where: string): string {
  const v = need(src, key, where);
  if (typeof v === "string") return v;
  throw new Error(`levels.json: ${where}."${key}" is not a string`);
}

function readBool(src: RawRecord, key: string, where: string): boolean {
  const v = need(src, key, where);
  if (typeof v === "boolean") return v;
  throw new Error(`levels.json: ${where}."${key}" is not a boolean`);
}

function readSpec(src: RawRecord, where: string): ObstacleSpecEntry[] {
  const v = need(src, "obstacleSpec", where);
  if (!Array.isArray(v)) throw new Error(`levels.json: ${where}.obstacleSpec is not a list`);
  return v.map((entry, i) => {
    if (entry === null || typeof entry !== "object" || Array.isArray(entry)) {
      throw new Error(`levels.json: ${where}.obstacleSpec[${i}] is not an object`);
    }
    const rec = entry as RawRecord;
    const kind = rec["type"];
    if (typeof kind !== "string") {
      throw new Error(`levels.json: ${where}.obstacleSpec[${i}] has no "type"`);
    }
    return { ...rec, type: kind } as ObstacleSpecEntry;
  });
}

function readTriple(src: RawRecord, key: string, where: string): [number, number, number] {
  const v = need(src, key, where);
  if (Array.isArray(v) && v.length === 3) {
    const a = v[0];
    const b = v[1];
    const c = v[2];
    if (typeof a === "number" && typeof b === "number" && typeof c === "number") {
      return [a, b, c];
    }
  }
  throw new Error(`levels.json: ${where}."${key}" is not a triple of numbers`);
}

/** Floats survive a JSON round-trip exactly, but the products do not. */
function nearlyEqual(a: number, b: number): boolean {
  return Math.abs(a - b) <= 1e-9 * Math.max(1.0, Math.abs(a), Math.abs(b));
}

function assertDerived(lv: LevelDef, src: RawRecord, where: string): void {
  const problems: string[] = [];
  const cruise = cruiseSpeedFor(lv.index);
  const base = cruise * lv.speedMult;
  const par = parScoreFor(lv.goalFood);
  const stars = starTargetsFor(par);
  const num = lv.index + 1;

  if (!nearlyEqual(readNum(src, "cruiseSpeed", where), cruise)) {
    problems.push(`cruiseSpeed ${src["cruiseSpeed"]} != recomputed ${cruise}`);
  }
  if (!nearlyEqual(readNum(src, "baseSpeed", where), base)) {
    problems.push(`baseSpeed ${src["baseSpeed"]} != recomputed ${base}`);
  }
  if (readNum(src, "parScore", where) !== par) {
    problems.push(`parScore ${src["parScore"]} != recomputed ${par}`);
  }
  const exported = readTriple(src, "starTargets", where);
  if (exported[0] !== stars[0] || exported[1] !== stars[1] || exported[2] !== stars[2]) {
    problems.push(`starTargets ${exported.join()} != recomputed ${stars.join()}`);
  }
  if (readNum(src, "number", where) !== num) {
    problems.push(`number ${src["number"]} != recomputed ${num}`);
  }
  if (problems.length > 0) {
    throw new Error(
      `levels.json is out of sync with config.json at ${where}: ${problems.join("; ")}`,
    );
  }
}

function buildLevel(src: RawRecord, position: number, total: number): LevelDef {
  const where = `levels[${position}]`;
  const index = Math.trunc(readNum(src, "index", where));
  if (index !== position) {
    throw new Error(`levels.json: ${where}.index is ${index}, expected ${position}`);
  }
  const themeIndex = Math.trunc(readNum(src, "themeIndex", where));
  if (themeIndex !== index) {
    throw new Error(`levels.json: ${where}.themeIndex is ${themeIndex}, expected ${index}`);
  }

  const lv: LevelDef = {
    index,
    name: readStr(src, "name", where),
    subtitle: readStr(src, "subtitle", where),
    theme: themeForLevel(themeIndex),
    goalFood: Math.trunc(readNum(src, "goalFood", where)),
    speedMult: readNum(src, "speedMult", where),
    foodCount: Math.trunc(readNum(src, "foodCount", where)),
    obstacleSpec: readSpec(src, where),
    powerupsEnabled: readBool(src, "powerupsEnabled", where),
    wrapWalls: readBool(src, "wrapWalls", where),
    hint: readStr(src, "hint", where),

    number: index + 1,
    difficultyRating: clamp(index / Math.max(1.0, total - 1), 0.0, 1.0),
    cruiseSpeed: cruiseSpeedFor(index),
    baseSpeed: cruiseSpeedFor(index) * readNum(src, "speedMult", where),
    parScore: parScoreFor(Math.trunc(readNum(src, "goalFood", where))),
    starTargets: starTargetsFor(parScoreFor(Math.trunc(readNum(src, "goalFood", where)))),
  };

  assertDerived(lv, src, where);
  return lv;
}

const rawDoc = rawLevels as unknown as { levels: RawRecord[] };
const rawList = rawDoc.levels;

/** The campaign: twelve levels, in order. */
export const LEVELS: readonly LevelDef[] = rawList.map((src, i) =>
  buildLevel(src, i, rawList.length),
);

/** How many levels the campaign has (12). */
export const LEVEL_COUNT: number = LEVELS.length;

/** Level names in campaign order, for menus and save-file labels. */
export const LEVEL_NAMES: readonly string[] = LEVELS.map((lv) => lv.name);

if (LEVEL_COUNT !== THEMES.length) {
  throw new Error(
    `levels.json has ${LEVEL_COUNT} levels but themes.json has ${THEMES.length} themes`,
  );
}

/** Level `i`, clamped into range. Never throws, never returns undefined. */
export function getLevel(i: number): LevelDef {
  let idx = Number.isFinite(i) ? Math.trunc(i) : 0;
  if (idx < 0) idx = 0;
  else if (idx >= LEVEL_COUNT) idx = LEVEL_COUNT - 1;
  const lv = LEVELS[idx];
  if (lv === undefined) throw new Error("no levels defined");
  return lv;
}

/** The whole campaign, in order. */
export function allLevels(): readonly LevelDef[] {
  return LEVELS;
}
