/**
 * Colour system for NEON SERPENT - a port of `snake/palette.py`.
 *
 * Every level owns a {@link Theme}: a small, coherent set of colours plus the
 * name of the background style that should be drawn behind it. Renderers never
 * invent colours - they pull them from the active theme so the whole frame
 * reads as one designed image instead of a pile of unrelated hues.
 *
 * Colours are plain RGB triples of ints 0..255, exactly as in Python. Because
 * Pixi wants packed `0xRRGGBB` numbers, every theme also carries a `hex` mirror
 * of its palette, converted **once at module load** rather than per frame.
 *
 * The twelve themes are loaded from `data/themes.json` (generated by
 * `tools/export_data.py`); nothing is retyped here.
 */

import rawThemes from "../data/themes.json";

/** An RGB colour, channels 0..255. */
export type RGB = readonly [number, number, number];

/** An RGBA colour, channels 0..255. */
export type RGBA = readonly [number, number, number, number];

// ---------------------------------------------------------------------------
// Colour maths (ported 1:1 from palette.py)
// ---------------------------------------------------------------------------

/** Clamp a number into a valid 0..255 channel value (truncating, like Python). */
export function clamp8(v: number): number {
  if (!Number.isFinite(v)) return 0;
  return v < 0 ? 0 : v > 255 ? 255 : Math.trunc(v);
}

/** Linear blend between two colours; `t` is clamped to 0..1. */
export function lerpColor(a: RGB, b: RGB, t: number): RGB {
  const k = t < 0 ? 0 : t > 1 ? 1 : t;
  return [
    clamp8(a[0] + (b[0] - a[0]) * k),
    clamp8(a[1] + (b[1] - a[1]) * k),
    clamp8(a[2] + (b[2] - a[2]) * k),
  ];
}

/** Multiply brightness. `factor` < 1 darkens, > 1 lightens (saturating). */
export function shade(c: RGB, factor: number): RGB {
  return [clamp8(c[0] * factor), clamp8(c[1] * factor), clamp8(c[2] * factor)];
}

/** Attach an alpha channel (0..255) to an RGB colour. */
export function withAlpha(c: RGB, a: number): RGBA {
  return [Math.trunc(c[0]), Math.trunc(c[1]), Math.trunc(c[2]), clamp8(a)];
}

/** Port of `colorsys.hsv_to_rgb`; h wraps, s and v are clamped to 0..1. */
function hsvToRgbFloat(h: number, s: number, v: number): [number, number, number] {
  if (s <= 0) return [v, v, v];
  const i = Math.floor(h * 6.0);
  const f = h * 6.0 - i;
  const p = v * (1.0 - s);
  const q = v * (1.0 - s * f);
  const t = v * (1.0 - s * (1.0 - f));
  switch (((i % 6) + 6) % 6) {
    case 0:
      return [v, t, p];
    case 1:
      return [q, v, p];
    case 2:
      return [p, v, t];
    case 3:
      return [p, q, v];
    case 4:
      return [t, p, v];
    default:
      return [v, p, q];
  }
}

/** Port of `colorsys.rgb_to_hsv`; inputs and outputs are floats in 0..1. */
function rgbToHsvFloat(r: number, g: number, b: number): [number, number, number] {
  const maxc = Math.max(r, g, b);
  const minc = Math.min(r, g, b);
  const rangec = maxc - minc;
  const v = maxc;
  if (minc === maxc) return [0.0, 0.0, v];
  const s = rangec / maxc;
  const rc = (maxc - r) / rangec;
  const gc = (maxc - g) / rangec;
  const bc = (maxc - b) / rangec;
  let h: number;
  if (r === maxc) h = bc - gc;
  else if (g === maxc) h = 2.0 + rc - bc;
  else h = 4.0 + gc - rc;
  h = (h / 6.0) % 1.0;
  if (h < 0) h += 1.0;
  return [h, s, v];
}

/** Build an RGB colour from HSV floats in 0..1 (h wraps). */
export function hsv(h: number, s: number, v: number): RGB {
  let hh = h % 1.0;
  if (hh < 0) hh += 1.0;
  const ss = Math.max(0.0, Math.min(1.0, s));
  const vv = Math.max(0.0, Math.min(1.0, v));
  const [r, g, b] = hsvToRgbFloat(hh, ss, vv);
  return [clamp8(r * 255), clamp8(g * 255), clamp8(b * 255)];
}

/** Rotate a colour's hue by `delta` turns (0..1), keeping S and V. */
export function hueShift(c: RGB, delta: number): RGB {
  const [h, s, v] = rgbToHsvFloat(c[0] / 255.0, c[1] / 255.0, c[2] / 255.0);
  return hsv(h + delta, s, v);
}

/** A point on a smooth rainbow; `t` is a free-running time value. */
export function rainbow(t: number, sat = 0.85, val = 1.0): RGB {
  return hsv(t, sat, val);
}

/** Pack an RGB triple into a `0xRRGGBB` number, which is what Pixi wants. */
export function toHex(c: RGB): number {
  return (clamp8(c[0]) << 16) | (clamp8(c[1]) << 8) | clamp8(c[2]);
}

// ---------------------------------------------------------------------------
// Theme
// ---------------------------------------------------------------------------

/** Every theme colour, packed as `0xRRGGBB` numbers for the renderer. */
export interface ThemeHex {
  readonly bgTop: number;
  readonly bgBottom: number;
  readonly grid: number;
  readonly accent: number;
  readonly accent2: number;
  readonly snakeHead: number;
  readonly snakeA: number;
  readonly snakeB: number;
  readonly food: number;
  readonly hazard: number;
  readonly text: number;
  readonly textDim: number;
}

/** The complete colour identity of one level. */
export interface Theme {
  readonly name: string;
  /** Key understood by the background renderer ("grid", "nebula", ...). */
  readonly bgStyle: string;
  /** Gradient sky colour, top of the arena. */
  readonly bgTop: RGB;
  /** Gradient colour at the bottom. */
  readonly bgBottom: RGB;
  /** Arena grid / lattice lines. */
  readonly grid: RGB;
  /** Primary neon: borders, highlights, UI focus. */
  readonly accent: RGB;
  /** Secondary neon: contrast pairings. */
  readonly accent2: RGB;
  readonly snakeHead: RGB;
  /** Body gradient start (head end). */
  readonly snakeA: RGB;
  /** Body gradient end (tail end). */
  readonly snakeB: RGB;
  readonly food: RGB;
  /** Walls, spikes, anything that hurts. */
  readonly hazard: RGB;
  readonly text: RGB;
  readonly textDim: RGB;
  /** The same palette as packed `0xRRGGBB` numbers, computed once at load. */
  readonly hex: ThemeHex;
}

/** Colour of a body segment: `t01` = 0 at the head, 1 at the tail tip. */
export function bodyAt(theme: Theme, t01: number): RGB {
  return lerpColor(theme.snakeA, theme.snakeB, t01);
}

// ---------------------------------------------------------------------------
// Loading the export
// ---------------------------------------------------------------------------

type RawRecord = Record<string, unknown>;

function readRgb(src: RawRecord, key: string): RGB {
  const v = src[key];
  if (Array.isArray(v) && v.length >= 3) {
    const r = v[0];
    const g = v[1];
    const b = v[2];
    if (typeof r === "number" && typeof g === "number" && typeof b === "number") {
      return [clamp8(r), clamp8(g), clamp8(b)];
    }
  }
  throw new Error(`themes.json: "${key}" is not an RGB triple`);
}

function readStr(src: RawRecord, key: string): string {
  const v = src[key];
  if (typeof v === "string") return v;
  throw new Error(`themes.json: "${key}" is not a string`);
}

function buildTheme(src: RawRecord): Theme {
  const bgTop = readRgb(src, "bg_top");
  const bgBottom = readRgb(src, "bg_bottom");
  const grid = readRgb(src, "grid");
  const accent = readRgb(src, "accent");
  const accent2 = readRgb(src, "accent2");
  const snakeHead = readRgb(src, "snake_head");
  const snakeA = readRgb(src, "snake_a");
  const snakeB = readRgb(src, "snake_b");
  const food = readRgb(src, "food");
  const hazard = readRgb(src, "hazard");
  const text = readRgb(src, "text");
  const textDim = readRgb(src, "text_dim");
  return {
    name: readStr(src, "name"),
    bgStyle: readStr(src, "bg_style"),
    bgTop,
    bgBottom,
    grid,
    accent,
    accent2,
    snakeHead,
    snakeA,
    snakeB,
    food,
    hazard,
    text,
    textDim,
    hex: {
      bgTop: toHex(bgTop),
      bgBottom: toHex(bgBottom),
      grid: toHex(grid),
      accent: toHex(accent),
      accent2: toHex(accent2),
      snakeHead: toHex(snakeHead),
      snakeA: toHex(snakeA),
      snakeB: toHex(snakeB),
      food: toHex(food),
      hazard: toHex(hazard),
      text: toHex(text),
      textDim: toHex(textDim),
    },
  };
}

const rawDoc = rawThemes as unknown as {
  themes: RawRecord[];
  ui: RawRecord;
};

/** The twelve level themes, ordered to match `LEVELS` in `core/level`. */
export const THEMES: readonly Theme[] = rawDoc.themes.map(buildTheme);

/** How many themes the export carried (12). */
export const THEME_COUNT: number = THEMES.length;

/** Theme for a zero-based level index; wraps for levels beyond the list. */
export function themeForLevel(index: number): Theme {
  if (THEMES.length === 0) throw new Error("no themes defined");
  const i = Number.isFinite(index) ? Math.trunc(index) : 0;
  const wrapped = ((i % THEMES.length) + THEMES.length) % THEMES.length;
  const theme = THEMES[wrapped];
  if (theme === undefined) throw new Error("no themes defined");
  return theme;
}

// ---------------------------------------------------------------------------
// Shared, theme-independent colours
// ---------------------------------------------------------------------------

function ui(key: string, fallback: RGB): RGB {
  const v = rawDoc.ui[key];
  if (Array.isArray(v) && v.length >= 3) return readRgb(rawDoc.ui, key);
  return fallback;
}

/** Panel fill behind HUD and menu chrome. */
export const UI_PANEL: RGB = ui("UI_PANEL", [16, 19, 34]);
/** Raised panel fill, one step lighter than {@link UI_PANEL}. */
export const UI_PANEL_LIGHT: RGB = ui("UI_PANEL_LIGHT", [28, 33, 56]);
/** Drop-shadow colour. Not exported by Python's data dump, so it is literal. */
export const UI_SHADOW: RGB = [0, 0, 0];
/** Primary text / bright chrome. */
export const UI_WHITE: RGB = ui("UI_WHITE", [240, 246, 255]);
/** Secondary, de-emphasised text. */
export const UI_DIM: RGB = ui("UI_DIM", [132, 146, 176]);
/** Success / positive feedback. */
export const UI_GOOD: RGB = ui("UI_GOOD", [86, 240, 160]);
/** Caution / timers running out. */
export const UI_WARN: RGB = ui("UI_WARN", [255, 196, 72]);
/** Damage / failure. */
export const UI_BAD: RGB = ui("UI_BAD", [255, 84, 108]);
/** Stars, records, celebration. */
export const UI_GOLD: RGB = ui("UI_GOLD", [255, 208, 84]);

/** The shared UI colours as packed `0xRRGGBB` numbers, computed once at load. */
export const UI_HEX = {
  panel: toHex(UI_PANEL),
  panelLight: toHex(UI_PANEL_LIGHT),
  shadow: toHex(UI_SHADOW),
  white: toHex(UI_WHITE),
  dim: toHex(UI_DIM),
  good: toHex(UI_GOOD),
  warn: toHex(UI_WARN),
  bad: toHex(UI_BAD),
  gold: toHex(UI_GOLD),
} as const;
